name: Docker Image Build

on:
  pull_request:
    branches:
    - main
    types:
    - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "ARM64"]
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    env:
      IMAGE_NAME: localhost:32000/hyuabot/hyuabot-kakao-server-python:latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: ${{ env.IMAGE_NAME }}
        no-cache: true
    - name: Push docker image
      run: |
        docker push ${{ env.IMAGE_NAME }}
